// <auto-generated />
namespace PersonalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatedthemodelstogetmorefeatures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedthemodelstogetmorefeatures));
        
        string IMigrationMetadata.Id
        {
            get { return "202412240041000_updated-the-models-to-get-more-features"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
