// <auto-generated />
namespace PersonalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addednewattributetoJobAdvertisment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addednewattributetoJobAdvertisment));
        
        string IMigrationMetadata.Id
        {
            get { return "202412251319289_added-new-attribute-to-JobAdvertisment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
