// <auto-generated />
namespace PersonalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class moved_attribute_from_derived_to_base_class : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(moved_attribute_from_derived_to_base_class));
        
        string IMigrationMetadata.Id
        {
            get { return "202412231912195_moved_attribute_from_derived_to_base_class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
